### ISSUE TITLE
npm install issue with grpc

### ISSUE THREAD

**Issue by tLupus1978** [mcintyrehh/MMM-Live-Stream-TV#12]
when executing in current branch, grpc build fails (in magicMirror docker)
`../deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc: In function ‘grpc_grpclb_request* grpc_grpclb_request_create(const char*)’:
../deps/grpc/src/core/ext/filters/client_channel/lb_policy/grpclb/load_balancer_api.cc:70:10: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 128 equals destination size [-Wstringop-truncation]
   strncpy(req->initial_request.name, lb_service_name,`

after searching https://github.com/grpc/grpc-node/issues/922 i figured out, that you must execute first
`npm install request`
and then
`npm install`
this does the trick

If you see a better approach, tell me. Nevertheless, streams are still not playing :-(

**Comment by mcintyrehh** [comment]
Sorry this is absurdly late but I've added the `request` package to package.json, and added an HLS proxy to the module to get around CORS/Permission errors! I'll be cleaning this repo up some more over the next week or so.

Thanks so much for the issue submission!
