### ISSUE TITLE
Stream does not play, maybe CORS issues?

### ISSUE THREAD

**Issue by tLupus1978** [mcintyrehh/MMM-Live-Stream-TV#6]
no stream at all plays with this module.
when checking in Chrome browser, I see that many CORS issues occurs:
`Access to XMLHttpRequest at 'https://www.earthcam.com/usa/newyork/midtown/skyline/?cam=midtown4k' from origin 'http://myserver:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

 do you have a solution for this or am I doing smth. wrong?
using Raspberry3b+

**Comment by mcintyrehh** [comment]
Sorry this is so late! I've just added a HLS proxy to the module to get around CORS/Permission errors! 

I'll be cleaning this repo up some more over the next week or so.

Thanks so much for the issue submission and let me know if you run into any more issues!
